spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/fourpillars"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    hibernate:
      #개발 환경에서 스키마 자동 업데이트. 프로덕션인 경우 validate 권장 create-drop
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

    database-platform: "org.hibernate.dialect.MariaDBDialect"
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_WEB_CLIENT_ID}"
            client-secret: "${GOOGLE_WEB_CLIENT_SECRET}"
            scope:
              - email
              - profile
            redirect-uri: "https://www.kolloseum.com/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google

jwt:
  secret: "${JWT_SECRET}"
  temporary-token-validity-in-seconds: 600
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
  issuer: "auth-service"

oauth:
  google:
    client-id: "${GOOGLE_CLIENT_ID}"
    client-secret: "${GOOGLE_CLIENT_SECRET}"
  kakao:
    client-id: "${KAKAO_CLIENT_ID}"
    client-secret: "${KAKAO_CLIENT_SECRET}"
  naver:
    client-id: "${NAVER_CLIENT_ID}"
    client-secret: "${NAVER_CLIENT_SECRET}"

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

server:
  forward-headers-strategy: native