spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

jwt:
  secret: "${JWT_SECRET}"
  temporary-token-validity-in-seconds: 600
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
  issuer: "auth-service"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_WEB_CLIENT_ID}"
            client-secret: "${GOOGLE_WEB_CLIENT_SECRET}"
            scope:
              - email
              - profile
            redirect-uri: "https://www.kolloseum.com/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google

oauth:
  google:
    client-id: "${GOOGLE_CLIENT_ID}"
    client-secret: "${GOOGLE_CLIENT_SECRET}"
  kakao:
    client-id: "${KAKAO_CLIENT_ID}"
    client-secret: "${KAKAO_CLIENT_SECRET}"
  naver:
    client-id: "${NAVER_CLIENT_ID}"
    client-secret: "${NAVER_CLIENT_SECRET}"
